### ISSUE TITLE
Epic: improve Kobo form integration

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#583]
This is a placeholder for a more complete description of a set of improvements to how we support Kobo forms and authentication to access form results

- [ ] https://github.com/WFP-VAM/prism-app/issues/564

- [ ] https://github.com/WFP-VAM/prism-app/issues/486

- [ ] https://github.com/WFP-VAM/prism-app/issues/487

- [ ] https://github.com/WFP-VAM/prism-app/issues/560

**Comment by ericboucher** [comment]
Since there is only one issue left, I am closing this and keeping #560
