### ISSUE TITLE
Epic: improve exposure analysis and reporting feature

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#632]
- [ ] https://github.com/WFP-VAM/prism-app/issues/631
- [ ] https://github.com/WFP-VAM/prism-app/issues/629
- [ ] https://github.com/WFP-VAM/prism-app/issues/622
